import streamlit as st
import requests, os, sqlite3, bcrypt, zipfile, io
from datetime import datetime
import matplotlib.pyplot as plt

# ======================
# DATABASE
# ======================

conn = sqlite3.connect("veera_ai.db", check_same_thread=False)
c = conn.cursor()

c.execute("""CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE,
    password BLOB)""")

c.execute("""CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT,
    title TEXT,
    content TEXT,
    created_at TEXT)""")

conn.commit()

# ======================
# AUTH
# ======================

def create_user(username, password):
    hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
    try:
        c.execute("INSERT INTO users (username, password) VALUES (?, ?)", (username, hashed))
        conn.commit()
        return True
    except:
        return False

def authenticate(username, password):
    c.execute("SELECT password FROM users WHERE username=?", (username,))
    row = c.fetchone()
    if row and bcrypt.checkpw(password.encode(), row[0]):
        return True
    return False

def login_ui():
    st.subheader("🔐 Login / Signup")
    tab1, tab2 = st.tabs(["Login", "Signup"])

    with tab1:
        u = st.text_input("Username")
        p = st.text_input("Password", type="password")
        if st.button("Login"):
            if authenticate(u, p):
                st.session_state.user = u
                st.rerun()
            else:
                st.error("Invalid credentials")

    with tab2:
        u = st.text_input("New Username")
        p = st.text_input("New Password", type="password")
        if st.button("Create Account"):
            if create_user(u, p):
                st.success("Account created")
            else:
                st.error("Username exists")

if "user" not in st.session_state:
    login_ui()
    st.stop()

# ======================
# MODEL ROUTER
# ======================

OPENROUTER_KEY = os.getenv("OPENROUTER_API_KEY")
URL = "https://openrouter.ai/api/v1/chat/completions"

def select_model(mode):
    if mode == "⚡ Fast":
        return "openai/gpt-4o-mini"
    elif mode == "وازن Balanced":
        return "meta-llama/llama-3-8b-instruct"
    else:
        return "anthropic/claude-3.5-sonnet"

def call_ai(prompt, model):
    if not OPENROUTER_KEY:
        return "Missing API key."

    try:
        r = requests.post(
            URL,
            headers={
                "Authorization": f"Bearer {OPENROUTER_KEY}",
                "Content-Type": "application/json"
            },
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}]
            },
            timeout=60
        )
        return r.json()["choices"][0]["message"]["content"]
    except:
        return "AI service unavailable."

# ======================
# MULTI-AGENT (OPTIONAL)
# ======================

def multi_agent_response(prompt, model):
    agents = {
        "planner": "Break into steps",
        "architect": "Design solution",
        "qa": "Find issues"
    }

    outputs = []
    for role in agents.values():
        outputs.append(call_ai(role + "\n" + prompt, model))

    merged = "\n".join(outputs)
    return call_ai("Combine into final answer:\n" + merged, model)

# ======================
# ZIP
# ======================

def create_zip(title, content):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as z:
        z.writestr("project.txt", content)
        z.writestr("README.md", f"# {title}\nGenerated by Veera AI")
    buf.seek(0)
    return buf

# ======================
# UI
# ======================

st.set_page_config("Veera AI Platform", layout="wide")
st.title("🚀 Veera Enterprise AI Platform")

# Sidebar performance settings
st.sidebar.subheader("⚙ Performance Mode")
mode = st.sidebar.radio(
    "Select mode",
    ["⚡ Fast", "وازن Balanced", "🏆 Quality"]
)

use_agents = st.sidebar.checkbox("Enable multi-agent reasoning")

model = select_model(mode)

tabs = st.tabs([
    "💬 AI Chat",
    "💻 Code Lab",
    "📁 Projects",
    "📊 Analytics"
])

# -------- CHAT --------
with tabs[0]:
    q = st.chat_input("Ask anything...")
    if q:
        if use_agents:
            ans = multi_agent_response(q, model)
        else:
            ans = call_ai(q, model)
        st.write(ans)

# -------- CODE LAB --------
with tabs[1]:
    task = st.text_area("Describe project")
    if st.button("Generate"):
        if use_agents:
            result = multi_agent_response(task, model)
        else:
            result = call_ai(task, model)

        title = task[:40]
        c.execute("INSERT INTO projects VALUES (NULL,?,?,?,?)",
                  (st.session_state.user, title, result, datetime.now().isoformat()))
        conn.commit()

        st.success("Project saved")
        st.write(result)

# -------- PROJECTS --------
with tabs[2]:
    c.execute("SELECT id,title,created_at FROM projects WHERE username=?",
              (st.session_state.user,))
    for pid, title, created in c.fetchall():
        if st.button(f"{title} ({created})", key=pid):
            c.execute("SELECT content FROM projects WHERE id=?", (pid,))
            content = c.fetchone()[0]
            st.write(content)
            st.download_button("Download ZIP", create_zip(title, content), f"{title}.zip")

# -------- ANALYTICS --------
with tabs[3]:
    c.execute("SELECT COUNT(*) FROM users")
    users = c.fetchone()[0]

    c.execute("SELECT COUNT(*) FROM projects")
    projects = c.fetchone()[0]

    st.metric("Users", users)
    st.metric("Projects", projects)

    fig, ax = plt.subplots()
    ax.bar(["Users", "Projects"], [users, projects])
    st.pyplot(fig)

# -------- LOGOUT --------
if st.sidebar.button("Logout"):
    st.session_state.clear()
    st.rerun()
